# @package _global_
module:
  _target_: emg2qwerty.lightning.CNNGRUCTCModule
  in_features: 528
  mlp_features: [384]
  cnn_channels: [256, 256]
  cnn_kernel_sizes: [5, 5]
  gru_hidden_size: 384
  gru_num_layers: 2
  dropout: 0.1
  bidirectional: true

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
